# Generated by Django 4.0.3 on 2022-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_data', models.DateTimeField()),
                ('text_body', models.TextField(verbose_name='text')),
                ('sources', models.TextField(blank=True)),
                ('sug_literature', models.TextField(blank=True)),
            ],
        ),
    ]
