# Generated by Django 4.0.3 on 2022-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='sources',
            field=models.TextField(blank=True, verbose_name='Sources'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sug_literature',
            field=models.TextField(blank=True, verbose_name='Suggested Literature'),
        ),
    ]
