# Generated by Django 4.0.3 on 2022-05-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_slug_article_title_alter_article_sources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Somebody', max_length=200),
            preserve_default=False,
        ),
    ]
