# Generated by Django 4.0.3 on 2022-05-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('articles', '0005_article_bookmarks_article_dislikes_article_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_articles', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_articles', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_articles', to='authentication.profile'),
        ),
    ]
