# Generated by Django 4.0.4 on 2022-05-14 12:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_bookmarks_alter_article_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_data',
            field=models.DateField(default=datetime.datetime(2022, 5, 14, 12, 18, 50, 715721, tzinfo=utc)),
        ),
    ]
