# Generated by Django 4.0.4 on 2022-05-15 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_article_pub_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='pub_data',
        ),
        migrations.AddField(
            model_name='article',
            name='last_edit_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 8, 38, 57, 650525, tzinfo=utc)),
        ),
    ]
