# Generated by Django 4.0.4 on 2022-05-17 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('articles', '0008_remove_article_pub_data_article_last_edit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_edit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_comments', to='authentication.profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article'),
        ),
    ]
